### ISSUE TITLE
Replace logger with aiologger

### ISSUE THREAD

**Issue by why-not-try-calmer** [KaratekHD/defrag#41]
_The built-in python logger is I/O blocking. This means that using the built-in logging module will interfere with your asynchronous application performance (__Adrien: which means that it interferes with profiling__). aiologger aims to be the standard Asynchronous non-blocking logging for python and asyncio._ Source: https://github.com/async-worker/aiologger

**Comment by why-not-try-calmer** [comment]
@KaratekHD Are you Ok to be assigned this task?

**Comment by KaratekHD** [comment]
Sure, that should be easy:

_If you want to generate all your logs asynchronously, you just have to change the instance of the logger object. To do that, all we need to change those lines from_
```python
from logging import getLogger
logger = getLogger(__name__)
```
_to:_

```python
from aiologger import Logger
logger = Logger.with_default_handlers()

```

**Comment by why-not-try-calmer** [comment]
LMAO Ok. I'll let you do it

**Comment by KaratekHD** [comment]
I'm working on it, it's not as easy as I thought though, since the new Logger can not be called in sync functions. (Which we have)

**Comment by why-not-try-calmer** [comment]
done as of #72
