### ISSUE TITLE
Repository permissions

### ISSUE THREAD

**Issue by KaratekHD** [KaratekHD/defrag#79]
@cboltz
Hey Christian,
sorry for pinning you.
could you please add @thunderbirdtr to this repository so that he can commit and merge PRs to it?
Also, can you give me permissions to change this repository's settings?
Thank you very much!

**Comment by cboltz** [comment]
Invitation sent.

I also upgraded your permissions. Use them wisely ;-)

**Comment by KaratekHD** [comment]
Awesome, thank you!
