### ISSUE TITLE
Python Dependency Manager: Pipenv?

### ISSUE THREAD

**Issue by why-not-try-calmer** [KaratekHD/defrag#8]
We do need a dep manager. There is the built-in virtualenv, Pipenv and others. I prefer Pipenv because it's very readable and intuitive. Are you Ok using it? If not, what alternative do you favor?

**Comment by KaratekHD** [comment]
I would actually prefer just to use virtualenv and pip, as it's the most easy way to do it.

**Comment by why-not-try-calmer** [comment]
Okay. Then the best approach is for everyone to use their favorite dep manager. I'll try not to pollute the code base with my Pipefile )
