### ISSUE TITLE
Other platforms than Telegram?

### ISSUE THREAD

**Issue by SingletonW** [KaratekHD/defrag#98]
Hi I am currently a CS student in Ireland (I am from from Belgium :) ) and I would be interested to contribute to this project!!

I have got in touch with @why-not-try-calmer on Matrix and he told me the conversation was on Telegram for the most part. Is there also somewhere on Matrix I can ask a few questions and, if you guys agree, get to contribute to this repository? I want to make sure I get the right ideas about the API before doing anything stupid :dancing_women:

**Comment by KaratekHD** [comment]
That's a good point, I will try to setup a bridged Matrix room as soon as possible. This might take a while though, as I need to request the bridge from the admins.
In the meantime, feel free to contact me @karatekhd:opensuse.org on Matrix or via email: karatekhd@opensuse.org

**Comment by why-not-try-calmer** [comment]
https://matrix.to/#/#oS_defrag_temporary:matrix.org is not up and running. As soon as KaratekHD is ready to setup a proper, more openSUSE compliant bridge, we'll migrate to it.

**Comment by KaratekHD** [comment]
@SingletonW Please try to join `#defrag:opensuse.org` (https://matrix.to/#/!KdiTLKYneqxObxzCnb:opensuse.org?via=opensuse.org&via=karatek.net&via=matrix.org) and let me know if that works for you.

**Comment by SingletonW** [comment]
Thank you very much! I just joined. I think I will close this issue then!
